require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

Layout/LineLength:
  Max: 100

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/MethodLength:
  Enabled: false
