require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

Layout/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
